[common]
server_addr = jp-osaka-1.lcf.im
server_port = 2333
tcp_mux = true
protocol = tcp
user = 4541044e77262dc38384de9c594db5a7

token = LoCyanToken
dns_server = 223.6.6.6
tls_enable = false

[jknksg]
privilege_mode = true
type = http
local_ip = 127.0.0.1
local_port = 1145
custom_domains = kna.test01.com 